### ISSUE TITLE
(Crunchyroll) Some old videos no longer download

### ISSUE THREAD

**Issue by SuperrSonic** [ytdl-org/youtube-dl#12152]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

```
$ youtube-dl -v <http://www.crunchyroll.com/galaxy-express-999/episode-26-the-skeletons-song-512670>
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.crunchyroll.com/galaxy-express-999/episo
de-26-the-skeletons-song-512670', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.16
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-50911-g9efcfbe, rtmpdump 2.5
[debug] Proxy map: {}
[Crunchyroll] 512670: Downloading webpage
[Crunchyroll] 512670: Downloading media info for 360p
[Crunchyroll] 512670: Downloading media info for 480p
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\bu
ild\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\bu
ild\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\bu
ild\youtube_dl\extractor\crunchyroll.py", line 449, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\bu
ild\youtube_dl\extractor\common.py", line 936, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.
...
<end of log>
```

Previously it was possible to download those videos. Titles I've found that can't be downloaded anymore:
Galaxy Express 999
Girl's High
Charger Girl Ju-den Chan
Kanokon

It just so happens that these titles are 480p only and lack soft subtitles, however other 480p titles without soft subs still work, like: Jubei-chan: The Ninja Girl, and Zatch Bell!.

**Comment by remitamine** [comment]
```
youtube-dl http://www.crunchyroll.com/galaxy-express-999/episode-26-the-skeletons-song-512670
[Crunchyroll] 512670: Downloading webpage
[Crunchyroll] 512670: Downloading media info for 360p
[Crunchyroll] 512670: Downloading m3u8 information
[Crunchyroll] 512670: Downloading media info for 480p
[Crunchyroll] 512670: Downloading m3u8 information
[Crunchyroll] 512670: Downloading media info
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 149
[download] Destination: Galaxy Express 999 Season 1 Episode 26 – The Skeleton's Song-512670.mp4
[download]   0.7% of ~82.55MiB at 73.60KiB/s ETA 24:29
```

**Comment by SuperrSonic** [comment]
How is that possible? I tested on multiple OSs, used VPN, tried other downloaders and nothing.

Is there anything else worth trying?

**Comment by mcerdeira** [comment]
Same error here:
`
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

`
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\build\youtube_dl\extractor\common.py", line 672, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by Starsam80** [comment]
Odd, I get a different error but it's solved by logging in:
```
youtube-dl http://www.crunchyroll.com/galaxy-express-999/episode-26-the-skeletons-song-512670
[Crunchyroll] 512670: Downloading webpage
ERROR: This is a sample clip. To watch the full video, start a free trial today!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl http://www.crunchyroll.com/galaxy-express-999/episode-26-the-skeletons-song-512670 --cookies ../.cookies/crunchyroll.txt
[Crunchyroll] 512670: Downloading webpage
[Crunchyroll] 512670: Downloading media info for 360p
[Crunchyroll] 512670: Downloading m3u8 information
[Crunchyroll] 512670: Downloading media info for 480p
[Crunchyroll] 512670: Downloading m3u8 information
[Crunchyroll] 512670: Downloading media info
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 149
[download] Destination: Galaxy Express 999 Season 1 Episode 26 – The Skeleton's Song-512670.mp4
[download] 100% of 109.63MiB in 01:07
[ffmpeg] Fixing malformated aac bitstream in "Galaxy Express 999 Season 1 Episode 26 – The Skeleton's Song-512670.mp4"
```

**Comment by SuperrSonic** [comment]
I just get the same error if logged in.

**Comment by JamesTheAwesomeDude** [comment]
@SuperrSonic is your account locked or expired or something?

Send us a log with
 * Git latest
 * Ubuntu 16.04 / Mint 18
 * Python 3
 * Verbose
 * With login  
(The logs don't include any sensitive data)

**Comment by SuperrSonic** [comment]
@JamesTheAwesomeDude Thank you very much! I don't know why I didn't give it a try before, I made a new account and can now download them again. I still don't understand the problem, I can watch the videos fine on the site with the old account. Not to mention being logged off didn't change anything.

I'm trying to remember if anything big changed in my account recently, the only thing I can think of is I had premium until a few weeks ago.

**Comment by JamesTheAwesomeDude** [comment]
@SuperrSonic Well, only Premium accounts can download HD video if I recall correctly. Could that be it?

**Comment by SuperrSonic** [comment]
That's true but those shows are only 480p, and though I was premium awhile ago I never tried downloading any video, I could download those videos before I was premium. Also I am able to watch it on the site like any other free video.

**Comment by bato3** [comment]
@remitamine this video is geo-restriced
https://screenshots.firefox.com/ZkmDEeFOTSAI5MaB/www.crunchyroll.com

Site redirect to main page and display message
``` html
<script type="text/javascript">
  Page.messaging_box_controller = new MessageBox({"render_to": "#message_box"});
  Page.messaging_box_controller.addItems([{"type":"error","message_body":"Sorry, this video is not available in your region due to licensing restrictions.","message_body_html":"Sorry, this video is not available in your region due to licensing restrictions.","data":null}]);
</script>
```
[full page html](https://pastebin.com/sy698snK)
