### ISSUE TITLE
【CeskaTelevize.CZ】 Download NO Longer Possible

### ISSUE THREAD

**Issue by NiesmialyGosc** [ytdl-org/youtube-dl#30172]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\DELL\video\TEST>youtube-dl --all-subs --convert-subs srt --retries 20000 -f hls-main-6272 -v https://www.ceskatelevize.cz/ivysilani/10111864738-hercule-poirot/211381467540018-tajemstvi-levneho-bytu
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--convert-subs', 'srt', '--retries', '20000', '-f', 'hls-main-6272', '-v', 'https://www.ceskatelevize.cz/ivysilani/10111864738-hercule-poirot/211381467540018-tajemstvi-levneho-bytu']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89508-g1f1207145a, ffprobe N-89508-g1f1207145a
[debug] Proxy map: {'https': 'https://192.168.49.1:8282', 'ftp': 'ftp://192.168.49.1:8282', 'http': 'http://192.168.49.1:8282'}
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading webpage
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2069, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\ceskatelevize.py", line 130, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2158, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: 'Error'

C:\Users\DELL\video\TEST>
```

## Description

I've tried https://www.ceskatelevize.cz/ivysilani/12878558019-desatero-hrichu/220381485260005-desatero-hrichu-ii as well & the download doesn't work either. Chances are that they have updated the video format?

Can we please have this looked into ASAP and make sure the solution is available for **Windows 10**, i.e. can we have an updated ALL-IN-ONE "**youtube-dl.exe**" file for us **Windows 10** users?

Thank you
NiesmialyGosc

**Comment by kikuyan** [comment]
Duplicate #30151, #30166

**Comment by NiesmialyGosc** [comment]
> Duplicate #30151, #30166

Thank you @kikuyan . May I know when we could get a fix or a temporary solution? One important video is due to expire on Nov 1st..

Thank you
NiesmialyGosc

**Comment by kikuyan** [comment]
I cannot explain all the steps precisely.

• Obtain source code of youtube-dl (install with `pip` or `git clone`, or download zip from the Code menu in https://github.com/ytdl-org/youtube-dl or https://github.com/ytdl-org/youtube-dl/releases and unzip)
• Find file `youtube_dl/extractor/ceskatelevize.py` and modify the line (or replace the file with https://raw.githubusercontent.com/ytdl-org/youtube-dl/8d89a7b4957791b455bcfbc7571078ac7212469d/youtube_dl/extractor/ceskatelevize.py )
• Run the modified version of youtube-dl (maybe `cd` or set `PYTHONPATH` variable to the top of youtube-dl then run `python -m youtube_dl`)

**Comment by NiesmialyGosc** [comment]
> I cannot explain all the steps precisely.
> 
> • Obtain source code of youtube-dl (install with `pip` or `git clone`, or download zip from the Code menu in https://github.com/ytdl-org/youtube-dl or https://github.com/ytdl-org/youtube-dl/releases and unzip) • Find file `youtube_dl/extractor/ceskatelevize.py` and modify the line (or replace the file with https://raw.githubusercontent.com/ytdl-org/youtube-dl/8d89a7b4957791b455bcfbc7571078ac7212469d/youtube_dl/extractor/ceskatelevize.py ) • Run the modified version of youtube-dl (maybe `cd` or set `PYTHONPATH` variable to the top of youtube-dl then run `python -m youtube_dl`)

Thank you @kikuyan! I think you're explaining the steps for Windows 10 right? If I use busybox.exe to emulate the Linux environment in my Windows system then it should be an easier fix? I replaced youtube_dl\extractor\ceskatelevize.py with this one: https://raw.githubusercontent.com/ytdl-org/youtube-dl/8d89a7b4957791b455bcfbc7571078ac7212469d/youtube_dl/extractor/ceskatelevize.py, but it seems this wouldn't fix the issue?

**Comment by NiesmialyGosc** [comment]
> I cannot explain all the steps precisely.
> 
> • Obtain source code of youtube-dl (install with `pip` or `git clone`, or download zip from the Code menu in https://github.com/ytdl-org/youtube-dl or https://github.com/ytdl-org/youtube-dl/releases and unzip) • Find file `youtube_dl/extractor/ceskatelevize.py` and modify the line (or replace the file with https://raw.githubusercontent.com/ytdl-org/youtube-dl/8d89a7b4957791b455bcfbc7571078ac7212469d/youtube_dl/extractor/ceskatelevize.py ) • Run the modified version of youtube-dl (maybe `cd` or set `PYTHONPATH` variable to the top of youtube-dl then run `python -m youtube_dl`)

Hi @kikuyan , I did replace the "ceskatelevize.py" file under youtube_dl\extractor, however, it wouldn't work..

`~/video/TEST1/youtube-dl $ youtube-dl --all-subs --convert-subs srt --retries 20000 https://www.ceskatelevize.cz/ivysilani/10111864738-hercule-poirot/211381467540018-tajemstvi-levneho-bytu
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading webpage
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading JSON metadata
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
~/video/TEST1/youtube-dl $ youtube-dl --all-subs --convert-subs srt --retries 20000 https://www.ceskatelevize.cz/ivysilani/10111864738-hercule-poirot/211381467540018-tajemstvi-levneho-bytu
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading webpage
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading JSON metadata
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
~/video/TEST1/ATTEMPT/youtube-dl $ youtube-dl --all-subs --convert-subs srt --retries 20000 https://www.ceskatelevize.cz/ivysilani/10111864738-hercule-poirot/211381467540018-tajemstvi-levneho-bytu
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading webpage
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading JSON metadata
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\__main__.py", line 19, in <module>
~/video/TEST1/ATTEMPT/youtube-dl $ youtube-dl --all-subs --convert-subs srt --retries 20000 -v https://www.ceskatelevize.cz/ivysilani/10111864738-hercule-poirot/211381467540018-tajemstvi-levneho-bytu
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--convert-subs', 'srt', '--retries', '20000', '-v', 'https://www.ceskatelevize.cz/ivysilani/10111864738-hercule-poirot/211381467540018-tajemstvi-levneho-bytu']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Windows-10-10.0.18363-SP0
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://192.168.49.1:8282', 'https': 'https://192.168.49.1:8282', 'ftp': 'ftp://192.168.49.1:8282'}
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading webpage
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading JSON metadata
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\__main__.py", line 19, in <module>
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 2068, in download
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\youtube_dl\extractor\ceskatelevize.py", line 130, in _real_extract
  File "C:\Users\DELL\video\TEST1\ATTEMPT\youtube-dl\youtube-dl\youtube_dl\utils.py", line 2158, in sanitized_Request
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 320, in __init__
    self.full_url = url
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 346, in full_url
    self._parse()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'Error'
~/video/TEST1/ATTEMPT/youtube-dl $`

**Comment by kikuyan** [comment]
.tar.gz is fine, but don't care the executable in it.
I don't know about Windows. But you ran `youtube-dl` as-is, probably the unmodified version was used. Try to follow the last line of my previous comment.

**Comment by NiesmialyGosc** [comment]
``

> .tar.gz is fine, but don't care the executable in it. I don't know about Windows. But you ran `youtube-dl` as-is, probably the unmodified version was used. Try to follow the last line of my previous comment.

Yeah it works!:) Thanks a ton @kikuyan it really helps!

Best Regards,
NiesmialyGosc

**Comment by kikuyan** [comment]
I don't know the general way. I would search issue reports and pull requests and sort by date.
If a pull request is found and using `git`, the content could be fetched easily. For #30154, like "git fetch origin pull/30154/head:_somebranchname_"

Please close this. Duplicate in any case.

**Comment by mischwitz** [comment]
Hi @kikuyan 
after replacement of ceskatelevize.py new error regarding video formats appeared:

[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading webpage
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading JSON metadata
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading JSON metadata
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)>
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading JSON metadata
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading JSON metadata
[CeskaTelevize] 211381467540018-tajemstvi-levneho-bytu: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "d:\youtube-dl\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "d:\youtube-dl\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "d:\youtube-dl\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "d:\youtube-dl\youtube_dl\extractor\ceskatelevize.py", line 201, in _real_extract
    self._sort_formats(e['formats'])
  File "d:\youtube-dl\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kikuyan** [comment]
@mischwitz 
OpenSSL linked to Python you are using may have been outdated.
Nothing to do with the fix.

Next yt-dlp release (don't know when of course) seems to include a fix to ceskatelevize.cz, you may want to wait if you have time.

**Comment by mcepl** [comment]
So, you are completely certain that when by adding the change from https://github.com/ytdl-org/youtube-dl/pull/30154
 everything got fixed, it is just a coincidence?

**Comment by asd123-007** [comment]
I dont have tools to modify and compile again. Could you please share the outcome (macOS)?

**Comment by mcepl** [comment]
> I dont have tools to modify and compile again. Could you please share the outcome (macOS)? Diky/thx

Sorry, I am a Linux user, I have added the patch to openSUSE package.

And yes, somebody mentioning it above, I needed to run the command multiple times, It always ended with those SSL errors, but fortunately youtube-dl preserves working files, so it is possible to continue.

**Comment by asd123-007** [comment]
Anyone?

**Comment by mischwitz** [comment]
> @mischwitz OpenSSL linked to Python you are using may have been outdated. Nothing to do with the fix.

I don't know: 'OpenSSL 1.1.1l  24 Aug 2021'
It doesn't seem to be outdated.

**Comment by kikuyan** [comment]
If there's not much time left to download the video, try `--no-check-certificate` option for a workaround.

**Comment by asd123-007** [comment]
> If there's not much time left to download the video, try `--no-check-certificate` option for a workaround.

could you pls compile fixed version? Windows or macOS? Thank you

**Comment by kikuyan** [comment]
I don't think it's a good idea to ask unknown person for a binary. Dangerous.

**Comment by pinochico** [comment]
Ok,

the fix is merged now in master for app:
https://github.com/yt-dlp/yt-dlp

if you install this app, then new python3 and PyInstaller on the Mac (by homebrew), clone project to localhost (I use FORK), you can create new binary.
I maked and now I can load from ceskatelevize :)

**Comment by NiesmialyGosc** [comment]
`~/video/TEST1/youtube-dl $ python -m youtube_dl --all-subs --convert-subs srt --retries 20000 -v https://www.ceskatelevize.cz/porady/10111864738-hercule-poirot/211381467540022/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--convert-subs', 'srt', '--retries', '20000', '-v', 'https://www.ceskatelevize.cz/porady/10111864738-hercule-poirot/211381467540022/']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg N-89508-g1f1207145a, ffprobe N-89508-g1f1207145a
[debug] Proxy map: {'http': 'http://192.168.236.222:8080', 'https': 'https://192.168.236.222:8080', 'ftp': 'ftp://192.168.236.222:8080'}
[CeskaTelevizePorady] 211381467540022: Downloading webpage
ERROR: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\DELL\video\TEST1\youtube-dl\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\DELL\video\TEST1\youtube-dl\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\DELL\video\TEST1\youtube-dl\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\DELL\video\TEST1\youtube-dl\youtube_dl\extractor\ceskatelevize.py", line 282, in _real_extract
    data_url = update_url_query(unescapeHTML(self._search_regex(
  File "C:\Users\DELL\video\TEST1\youtube-dl\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

~/video/TEST1/youtube-dl $`

**Comment by asd123-007** [comment]
One note: 
-  ceskatelevize has some videos with DRM and some without.
-  You can try https://www.ceskatelevize.cz/porady/899326-mala-nocni-povidka/26153114926/ , which should be "without" DRM

But agree with the post above, something has changed now, again. Youtube-dl is still unable, and yt-dlp is unable since now.

**Comment by mcepl** [comment]
Something has certainly changed, I was able to download https://www.ceskatelevize.cz/ivysilani/10116288835-z-metropole/ on Saturday, but I cannot do it now. And it should be completely open, DRM-free program.

**Comment by NiesmialyGosc** [comment]
> One note:
> 
> * ceskatelevize has some videos with DRM and some without.
> * You can try https://www.ceskatelevize.cz/porady/899326-mala-nocni-povidka/26153114926/ , which should be "without" DRM
> 
> But agree with the post above, something has changed now, again. Youtube-dl is still unable, and yt-dlp is unable since now.

The episode "Plymouthský expres" is only visible from within the app..

**Comment by georgjaehnig** [comment]
I suggest the best video(s) to check are the news. They should be always DRM-free, and accessible from everywhere.

Like this one: https://www.ceskatelevize.cz/porady/1097181328-udalosti/221411000101209/

**Comment by benabraham** [comment]
unfortunately not working with the latest release

```
youtube-dl --verbose https://www.ceskatelevize.cz/porady/1097181328-udalosti/221411000101209/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ceskatelevize.cz/porady/1097181328-udalosti/221411000101209/']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[CeskaTelevizePorady] 221411000101209: Downloading webpage
ERROR: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\ceskatelevize.py", line 285, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by benabraham** [comment]
same for linux version
```
youtube-dl --verbose https://www.ceskatelevize.cz/porady/1097181328-udalosti/221411000101209/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.ceskatelevize.cz/porady/1097181328-udalosti/221411000101209/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.3.2-0york0, ffprobe 4.3.2-0york0
[debug] Proxy map: {}
[CeskaTelevizePorady] 221411000101209: Downloading webpage
ERROR: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ceskatelevize.py", line 285, in _real_extract
    webpage, 'iframe player url', group='url')), query={
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by vpodzime** [comment]
Instead of extracting the `iframe player url` from the webpage, it now needs to be constructed as follows:
1. A query to `https://www.ceskatelevize.cz/v-api/iframe-hash/` is needed with a `Referer` header equal to the URL (e.g. `https://www.ceskatelevize.cz/porady/10441294653-hyde-park-civilizace/217411058090506/`) which returns the iframe player hash
2. The iframe player URL is then in the following format: `https://www.ceskatelevize.cz/ivysilani/embed/iFramePlayer.php?hash=THE_HASH_RETURNED_BY_THE_API&origin=iVysilani&autoStart=true&width=100%25&IDEC=217411058090506&start=0`

**Comment by georgjaehnig** [comment]
@vpodzime Someone fixed it already for yt-dlp:

https://github.com/yt-dlp/yt-dlp/commit/443b21dc4e499286df3852f88fbd48e7f61b1f6a#diff-77727401d445bb2863b8509fa248a57e8a7d4e8aa71766d7ef269376b52c6229

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by mcepl** [comment]
> Issue should be closed, URL is dead

There are plenty of other URLs to test, but it seems that with https://github.com/ytdl-org/youtube-dl/pull/30713 it works just fine. At least I can download https://www.ceskatelevize.cz/porady/1097181328-udalosti/221411000101209/ (yes, it takes multiple tries to get, because the download crashes, but I got the whole show).
