### ISSUE TITLE
youtube_dl.utils.ExtractorError: Could not find JS function 'na'

### ISSUE THREAD

**Issue by MantisTree** [ytdl-org/youtube-dl#30363]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --verbose https://youtu.be/nXPyDlvZ1oQ
[debug] System config: []
[debug] User config: ['--format', 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '--merge-output-format', 'mp4', '-o', '/data/data/com.termux/files/home/storage/dcim/Camera/%(extractor_key)s-%(uploader)s-%(title)s-%(id)s.%(ext)s', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/nXPyDlvZ1oQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.1 (CPython) - Linux-4.14.190-22338387-abN975USQS7FUI6-aarch64-with-libc
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] nXPyDlvZ1oQ: Downloading webpage
[youtube] nXPyDlvZ1oQ: Downloading player 204bfffb
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1358, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying to download video with either url or just video code returns the indicated error

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
youtube nXPyDlvZ1oQ
~~~

https://github.com/89z/mech

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30364

**Comment by coletdjnz** [comment]
Looks like youtube-dl needs to update the signature function regex. 

There is no issue in yt-dlp, seems like this was avoided by https://github.com/yt-dlp/yt-dlp/pull/641.

Back-porting them from yt-dlp works. Relevant code:
https://github.com/yt-dlp/yt-dlp/blob/0bb322b9c0aebb7e0a93a5de1dbede4acdd10ff5/yt_dlp/extractor/youtube.py#L1828-L1845

**Comment by stevenroose** [comment]
Having the same issue when trying to resume from an existing partial download.

**Comment by sumit2089** [comment]
Ran into the same issue when tried to use youtube-dl with audio-format mp3
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--extract-audio', u'--verbose', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=9e6JBaFuf_w']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Darwin-21.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
```
With yt-dlp though, this problem does not occur.

**Comment by desmeraldoo** [comment]
I am also having this issue, which is impacting Discord bot I maintain.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=fnlJw9H0xAM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Linux-5.4.0-91-generic-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
```

**Comment by RedBreloom** [comment]
I am having this extraction/ no 'na' function issue too, but i'm not very savvy with code or python at all. Is there a way to fix this for the windows executable at the moment or would it need to be updated specifically?

**Comment by taylrfnt** [comment]
confirmed yt-dlp pull request above fixed this issue for me.  Must have been youtube switching their 2 char lookup?

**Comment by Marcioghiraldelli** [comment]
I also have this problem of not being able to download more videos or mp3 audios.

**Comment by another-dumb-user** [comment]
Having this issue with most youtube URLs (succeeded in downloading one of my own uploads) I think like others here

```
youtube-dl -f 140 --verbose https://www.youtube.com/watch?v=IC9CZyHLn3M
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '140', '--verbose', 'https://www.youtube.com/watch?v=IC9CZyHLn3M']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.10.1 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] IC9CZyHLn3M: Downloading webpage
[youtube] IC9CZyHLn3M: Downloading player 204bfffb
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1358, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by lanegramling** [comment]
I have submitted a PR (#30363) that resolves this issue. It looks like no PRs have been merged to master in quite some time now, so if you're really in a pinch to resolve this quickly, consider making the changes yourself to extractor/youtube.py in your local environments according to the changes in #30363, as it is a simple fix (if you are brazen enough to do so).

The problem lies in that Youtube has apparently made some change in their base.js such that the signature parser is taking issue with changes evident in the function signature format. Most are 2 characters (as the regex in the parser assumes) but it seems that 2 characters can no longer be assumed after their update for these signatures. Just needed to tweak the regex to account for that, and I haven't been able to replicate any of these issues since. You can see this for yourself by reviewing base.js at this link: https://www.youtube.com/s/player/850eb2bc/player_ias.vflset/en_US/base.js

Note that this finding was originally made in this PR for yt-dlp and is not mine: yt-dlp/yt-dlp#641. This fix for yt-dlp was spotted by @coletdjnz (good spot) in his earlier comment to this thread.

**Comment by philippkeller** [comment]
the link to @lanegramling  PR is wrong, to see what @lanegramling has changed to reapply to local files see https://github.com/ytdl-org/youtube-dl/pull/30366/commits/1a091687c248b62c2f0a6070519bd78417828746

**Comment by lanegramling** [comment]
> the link to @lanegramling PR is wrong, to see what @lanegramling has changed to reapply to local files see [1a09168](https://github.com/ytdl-org/youtube-dl/commit/1a091687c248b62c2f0a6070519bd78417828746)

Good catch, thanks for letting me know. I have updated the links in my comment.

**Comment by dirkf** [comment]
Fixed in PR #30363, single file signature+unthrottling update from PR #30184.

**Comment by UnixCro** [comment]
Allright. But how I can install the fixed version?

**Comment by dirkf** [comment]
Review [this issue](https://github.com/ytdl-org/youtube-dl/issues/29326). It may take some time.

TL;DR If you have patched against that throttling issue (I don't imagine you would be using yt-dl otherwise), just repeat the procedure.

**Comment by PaulCl99** [comment]
same problem here

**Comment by harishpillay** [comment]
Same issue on Fedora 35:

``` $ youtube-dl --verbose https://www.youtube.com/watch?v=kHjzuqq3b44
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=kHjzuqq3b44']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.10.0 (CPython) - Linux-5.15.6-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Proxy map: {}
[youtube] kHjzuqq3b44: Downloading webpage
[youtube] kHjzuqq3b44: Downloading player 204bfffb
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 835, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1358, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
As your yt-dl is in `site-packages`, it's not a Fedora issue (if the distro had installed it, it would be in `dist-packages`).

You can apply the [single file update](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994731986) over `/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py`.

**Comment by Devnol** [comment]
Same issue, macOS Monterey

**Comment by MaximFedarau** [comment]
So, is there any solution or patch?

**Comment by lanegramling** [comment]
> So, is there any solution or patch?

I have posted the solution in this thread above. For now you will have to implement it yourself in your local environment. It is a simple change. No PRs have been merged to master in months, so we can't really expect a fix to be merged through the official channels in any reasonable amount of time.

**Comment by hilbix** [comment]
For the benefit of the impatient reader,
here is how I applied the single file fix of PR #30366
to the lastest binary `youtube-dl` on Linux:

```bash
$ ./youtube-dl $VIDEO
# fails with something like: ExtractorError: Could not find JS function u'na';

$ ./youtube-dl -U
youtube-dl is up-to-date (2021.06.06)

$ mkdir -p youtube_dl/extractor
$ wget -O youtube_dl/extractor/youtube.py https://github.com/ytdl-org/youtube-dl/raw/1a091687c248b62c2f0a6070519bd78417828746/youtube_dl/extractor/youtube.py
$ tail +2 youtube-dl > youtube-dl.zip 
$ zip youtube-dl.zip youtube_dl/extractor/youtube.py 
updating: youtube_dl/extractor/youtube.py (deflated 77%)
$ { head -1 youtube-dl; cat youtube-dl.zip; } > youtube-dl.fixed
$ chmod +x youtube-dl.fixed

$ ./youtube-dl.fixed $VIDEO
# works
```

Notes:

- https://github.com/ytdl-org/youtube-dl/raw/1a091687c248b62c2f0a6070519bd78417828746/youtube_dl/extractor/youtube.py is the URL of the fixed file of the PR.
  **Do not trust me, compare yourself!**
- Sorry, I do not know how to fix this on Windows.
- Be sure to use `wget -O` (big Oh) and not `wget -o` (small o).
- However **my download still is below 100 KB/s**, even that PR suggests that this should have been fixed, too.

**Comment by Ashish2000L** [comment]
> Fixed in PR #30366, single file signature+unthrottling update from PR #30184.

Can anyone create a new repo for youtube_dl with fixes so that I can download updated file

**Comment by dirkf** [comment]
>     * https://github.com/ytdl-org/youtube-dl/raw/1a091687c248b62c2f0a6070519bd78417828746/youtube_dl/extractor/youtube.py is the URL of the fixed file of the PR.

To fix the throttling issue too, use the file linked from PR #30184 (which is a much bigger change), as explained [above](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994731986).

**Comment by snibbo71** [comment]
Can only assume I've done something wrong as I've downloaded the new youtube.py files and placed them in the dist-packages directory (which according to mlocate is the only place the youtube.py file exists on my system) and I'm still getting the same error.

Can anyone give me a clue what I've done wrong here? I'm really not familiar with python, so it's quite likely I screwed something up :)

TIA

**Comment by dirkf** [comment]
Whatever file you used wasn't the right version (missing the fix for this issue). Maybe you need to refresh your browser cache.

The correct one is linked from the Description text of PR #30184, corresponding to commit 3b9b1cd.

**Comment by snibbo71** [comment]
> Whatever file you used wasn't the right version (missing the fix for this issue). Maybe you need to refresh your browser cache.
> 
> The correct one is linked from the Description text of PR #30184, corresponding to commit [3b9b1cd](https://github.com/ytdl-org/youtube-dl/commit/3b9b1cd4314f9d44630a2a65abfff8abab454887).

I copied the URL you linked above and used wget, no browser cache involved...

There's no python cache or anything? (Sorry, I know that sounds a dumb question... I'm pretty good with Linux but no experience with python).

**Comment by fstirlitz** [comment]
If only there were some way to organise a hodgepodge of random patches into a derivative project.

**Comment by snibbo71** [comment]
Ah, I've managed to get mine working by following @hilbix instructions - because my youtube-dl is a binary that needed patching :)

One of the problems of failing memory as I get older... I couldn't remember how I installed it, so presumably I used a binary from the distro (Ubuntu 20.04).

Thanks for everyone's patience who's had to read my witterings :)

**Comment by hilbix** [comment]
@dirkf Thanks for the hint and sorry for me getting it wrong at first.  My bad English.

[Updated my comment](#issuecomment-994952040) with a script which patches both files from the other PR.

To all others:

- It is meant to be used with the Linux binary (zipped Python) for Linux (and probably Mac) version 2021.06.06 which must be named `youtube-dl` and must reside in the current directory
- You need to run `./youtube-dl.fixed` afterwards, as the script does not overwrite the precious `youtube-dl` original.
- It's a quick hack without proper error processing.  So if something breaks, you are left alone, sorry.

**Comment by MaximFedarau** [comment]
Thanks for fixing. Hopefully I am just studying programming and making my pet-project, but i hope, that creators are going to add your solution soon. :)

**Comment by kiplingw** [comment]
> > Fixed in PR #30366, single file signature+unthrottling update from PR #30184.
> 
> Can anyone create a new repo for youtube_dl with fixes so that I can download updated file

What we really need is a PPA of a nightly binary.

**Comment by nilbacardit26** [comment]
For those that are struggling and are here for an easy fix as @lanegramling did a PR in the original repo, and forked it as well:

1) `git clone https://github.com/lanegramling/youtube-dl.git`
2) `cd youtube_dl`
3) `pip install -e .`
4) `./youtube-dl {youtube_url}`

**Comment by 000011111111** [comment]
> Same issue, macOS Monterey

I have the same issue on macOS Monterey version 12.1  as of 12/15/2021

` youtube-dl -x --audio-format mp3 https://youtu.be/UXUwLyX6sUg

[youtube] UXUwLyX6sUg: Downloading webpage
[youtube] UXUwLyX6sUg: Downloading player 204bfffb
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1349, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output`

**Comment by dirkf** [comment]
[This comment](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994907769), but with `/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py`.

**Comment by DannyBen** [comment]
Correction to [this helpful comment](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-995093694):

`git clone --depth 1 --branch fix-function-sig-parser https://github.com/lanegramling/youtube-dl.git`

**Comment by erosenberg88** [comment]
> 

This is showing it as a directory.  I have followed along with the updates today, and appreciate them, but so far every change I make, even manually changing the youtube.py file, im still getting the same error as before :(

**Comment by Marcioghiraldelli** [comment]
@erosenberg88  I made all the changes above and none worked for my case, I use hundreds 7 as a base.

the installation was done in the standard way
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

I can't make it work at all.

**Comment by erosenberg88** [comment]
@Marcioghiraldelli  yuuuuuuup haha... hopefully they will have a good patch/update soon and we can have it working again!  But for now ¯\_(ツ)_/¯

**Comment by 000011111111** [comment]
> For those that are struggling and are here for an easy fix as @lanegramling did a PR in the original repo, and forked it as well:
> 
> 1. `git clone https://github.com/lanegramling/youtube-dl.git`
> 2. `cd youtube_dl`

on macOS 12.1 I get to step to and get the following error;

bash-3.2# cd youtube_dl
bash: cd: youtube_dl: **No such file or directory**

What is the best way to open youtube_dl when the computer does not read it as a file?

**Comment by dirkf** [comment]
Should be `cd youtube-dl`, I guess.

The cloned repo will be like this 
```
youtube-dl
     +---------bin
     +---------devscripts
     +---------docs
     +---------test
     +---------youtube_dl
                    +---------downloader
                    +---------extractor
                    +---------postprocessor
                    +--------- ...
     +--------- ...
```

**Comment by lanegramling** [comment]
> @erosenberg88 I made all the changes above and none worked for my case, I use hundreds 7 as a base.
> 
> the installation was done in the standard way sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl sudo chmod a+rx /usr/local/bin/youtube-dl
> 
> I can't make it work at all.

If I am understanding correctly, you are downloading the latest youtube-dl from the mirror on the website. This will not work as the fix is not present in that version. You will want to either replace the youtube-dl/extractor/youtube.py with the version in #30366 or just use the fork that this fix is present in, which is available at https://github.com/lanegramling/youtube-dl/tree/fix-function-sig-parser

**Comment by lanegramling** [comment]
> > For those that are struggling and are here for an easy fix as @lanegramling did a PR in the original repo, and forked it as well:
> 
> git clone https://github.com/lanegramling/youtube-dl.git cd youtube_dl pip install -e . ./youtube-dl {youtube_url}
> 
> This is showing it as a directory. I have followed along with the updates today, and appreciate them, but so far every change I make, even manually changing the youtube.py file, im still getting the same error as before :(

Not sure what the issue is, but consider double checking that you are cloning off the correct branch with my repo - you want to use the "fix-function-sig-parser" branch.

**Comment by UnixCro** [comment]
Man, I would be proud if I were the owner of youtube-dl.  The owner is famous for this other one. My mail folder is already overflowing when it comes to mails.

**Comment by dirkf** [comment]
Or you can unzip https://github.com/ytdl-org/youtube-dl/archive/3b9b1cd4314f9d44630a2a65abfff8abab454887.zip to get the current unthrottled update with the fix for this issue rolled in.

**Comment by Roman-33** [comment]
how can you get a fix if you don't know any python? how should i install and use the here above mentioned .zip file?


> Or you can unzip https://github.com/ytdl-org/youtube-dl/archive/3b9b1cd4314f9d44630a2a65abfff8abab454887.zip to get the current unthrottled update with the fix for this issue rolled in.

**Comment by C4H7Cl2O4P** [comment]
Whatever changes I put in youtube.py it shows me all the same error message
_ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1349, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/bin/youtube-dl/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'na'; please repo..._
even if I move lines with empty comment lines I still get error in same lines (1349, 1262, 1331) even if line 1331 in youtube.py is filled with my empty comment.
I have already restarted apache2 (I run youtube-dl by wsgi python script). Then I restarted my PC. All was useless.

Please, somebody, explaine me what is going on ?

**Comment by lanegramling** [comment]
> Whatever changes I put in youtube.py it shows me all the same error message ....... ERROR: Signature extraction failed: Traceback (most recent call last): File "/usr/local/bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1349, in _decrypt_signature video_id, player_url, s File "/usr/local/bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function res = self._parse_sig_js(code) File "/usr/local/bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js initial_function = jsi.extract_function(funcname) File "/usr/local/bin/youtube-dl/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function raise ExtractorError('Could not find JS function %r' % funcname) ExtractorError: Could not find JS function u'na'; please repo... ....... even if I move lines with empty comment lines I still get error in same lines (1349, 1262, 1331) even if line 1331 in youtube.py is filled with my empty comment. I have already restarted apache2 (I run youtube-dl by wsgi python script). Then I restarted my PC. All was useless.
> 
> Please, somebody, explaine me what is going on ?


Hard to say exactly, but consider checking if your changes are actually writing to the file on disk in this directory (and that you are writing to the youtube.py specifically mentioned in your tracebacks. That would be **/usr/local/bin/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py**. 

> 
> PS: There is one more strange thing. I do not have "/usr/local/bin/youtube-dl/youtube-dl/youtube_dl..." but "/usr/local/bin/youtube-dl/youtube_dl"

This sounds like something is awry with your package installation. I would probably uninstall and reinstall the package and then double check if there are abnormalities with the directory structure. There might be a nested copy of the repo hiding inside the base directory of another one, by the look of this.

**Comment by 2V3EvG4LMJFdRe** [comment]
Damn, this is a mess. I can't find any comment for a fix of youtube-dl installed with brew on macOS. Could someone point me to it?

**Comment by jimlynnjulian** [comment]
> Allright. But how I can install the fixed version?

Good question. Why no answer?

**Comment by jimlynnjulian** [comment]
When will the Windows binary reflect the change?

**Comment by dirkf** [comment]
The principles are set out in a series of comments in issue #29326, but may be tedious to find.

TL;DR

1 Your system is Unix-like (Linux, Mac OS, BSD, ...) and your installation is unpacked

Run `ls -l "$(which youtube-dl)"`. If the file is a small one, you probably have an unpacked installation where the `youtube.py` file can be replaced directly.

You can find the `youtube.py` file to replace by running a failing yt-dl command (should be easy at this point) with the `-v` aka `--verbose` option, as with OP's log that contains:
```
...
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
...
```
Here you can see that the full path of the file to be updated; the program installation is in `/data/data/com.termux/files/usr/lib/python3.9/site-packages`.

You also see that the file is in a system directory so you need to acquiring admin privilege (eg, `sudo`); this won't be relevant if the installation is under your home directory. As admin, replace the `youtube.py` file and run `youtube-dl --version` to ensure that any cached compiled version of the updated file is also updated. For a non-admin installation, this will happen when you first run the modified program.

2 Your system is Unix-like (Linux, Mac OS, BSD, ...) and your installation is a single self-extracting executable

The executable `youtube-dl` will be more than 1MB. You can unpack, update and repack the executable archive using a procedure as described [above](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994952040).

3 Your system is Windows

You almost certainly have a single executable file ~8MB (even if installed by Chocolatey) and it is possible to [update this self-extracting archive](https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-981108888).

4 Regardless of OS your yt-dl is installed by native Python tools (`pip`,. eg)

You can use a similar approach to # 1 above, or download the repo level corresponding to one of the PR fixes and install it yourself (`pip` examples above) or run `python -m youtube_dl` in the `youtube-dl` directory of the extracted zipped repo.

My bet is that Brew installs a Unix-like self-extracting executable as in # 2.

**Comment by jheled** [comment]
None of the suggested "fixes" works for me

**Comment by dirkf** [comment]
Give us a hint about what kind of installation you have and updating it failed.

**Comment by jimlynnjulian** [comment]
case: 3 Your system is Windows
"You almost certainly have a single executable file ~8MB (even if installed by Chocolatey) and it is possible to update this self-extracting archive."

Thelink you point to does not contain an executable.
As I mentioned, I have the latest, 6-6-21, installed. Still fails.
Can you give me a direct and concise answer about when and where to find a Windows binary that has been 'fixed'?

**Comment by gudiandian** [comment]
> 4\. ./youtube-dl {youtube_url}

This does not work for me on MacOS. It seems that the newest PR does not work as well.

**Comment by dirkf** [comment]
>Can you give me a direct and concise answer about when and where to find a Windows binary that has been 'fixed'?

Follow the suggested procedure in the link and you will magically find the fixed binary on your system.

>This does not work for me on MacOS. It seems that the newest PR does not work as well.

You can take it as read that the fixes work, until YT breaks itself again. So you should explain your update procedure and how it failed.

**Comment by jimlynnjulian** [comment]
> > Can you give me a direct and concise answer about when and where to find a Windows binary that has been 'fixed'?
> 
> Follow the suggested procedure in the link and you will magically find the fixed binary on your system.
> 
I'll take that as a no.

**Comment by kevinburke** [comment]
The normal release channels are all downstream of commits to the master branch of this repository.

No one has merged any patches to this library since June, let alone the patch to fix this specific issue.

I think that's the fundamental issue that no one has any clear suggestions on how to remedy.

**Comment by jheled** [comment]
Real shame. It is a tool I use daily. No it is unfunctional for (probably) a long time

**Comment by lanegramling** [comment]
@2V3EvG4LMJFdRe
> Damn, this is a mess. I can't find any comment for a fix of youtube-dl installed with brew on macOS. Could someone point me to it?

OS should be independent of the issue, but how and where to apply the fix will vary depending on your OS and environment. You will not be able to use brew to handily install the fixed version until the PR merges and flows through CI etc. Which will probably never happen, because the last merge on the master branch was like 6 months ago. So, to fix this: if you're using the package, you can modify the files per the instructions laid out earlier in this thread by either @dirkf or myself.

@gudiandian
> This does not work for me on MacOS. It seems that the newest PR does not work as well.
> 
> > For those that are struggling and are here for an easy fix as @lanegramling did a PR in the original repo, and forked it as well:
> > 
> > 1. `git clone https://github.com/lanegramling/youtube-dl.git`
> > 2. `cd youtube_dl`
> > 3. `pip install -e .`
> > 4. `./youtube-dl {youtube_url}`

OS should be independent of the issue, but how and where to apply the fix will vary depending on your OS and environment. Consider double checking that you are installing from the correct branch of https://github.com/lanegramling/youtube-dl.git. You will want to use the fix-function-sig-parser branch.

jimlynnjulian
> > > Can you give me a direct and concise answer about when and where to find a Windows binary that has been 'fixed'?
> > 
> > 
> > Follow the suggested procedure in the link and you will magically find the fixed binary on your system.
> 
> I'll take that as a no.

You're up a creek without a paddle here, as we all are, to fend for ourselves. The master branch has not seen anything new in 6 months. So there is no existence of the one-step solution to reclaiming a binary you seek. You will have to follow the extra steps to create/collect one yourself if you want to use a binary version. He laid out a great step-by-step, unfortunately your only choices are A) follow it, B) wait indefinitely (likely months or never) for the miraculous return of someone that can pull it into master, or C) switch packages and update your codebases to support the migration. All of the options are bad options, unfortunately...

**Comment by CagesThrottleUs** [comment]
> 3 Your system is Windows
> 
> You almost certainly have a single executable file ~8MB (even if installed by Chocolatey) and it is possible to [update this self-extracting archive](https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-981108888).

Ok so for this it asks about getting winRAR but unfortunately I use 7zip even though it says that it does not work in that case, is there no other fix for this, or do I have to download the master branch and build the tools?

**Comment by lanegramling** [comment]
> The normal release channels are all downstream of commits to the master branch of this repository.
> 
> No one has merged any patches to this library since June, let alone the patch to fix this specific issue.
> 
> I think that's the fundamental issue that no one has any clear suggestions on how to remedy.

I just want to call more attention to this, because I agree 100%. Realistically, the portion of people that seem to be having this issue is enough, combined with the apparent level of inactivity on the master branch, that they together indicate this repository is likely in its death throes. 

If you are having this issue and you care about your software working in the long term, take this as a sign to find a replacement library to use in your software. There are actively maintained forks of this project available (but they aren't necessarily painless migrations), so consider those. If you just want to slap in this hotfix like a band-aid on your low-impact personal project and keep moving, that's where the fixes discussed in this thread become useful. 

In reality, it is not often a wise decision to start fiddling with the internals of your environment's python packages without being well aware of what you're doing and its consequences, because you can cause big problems with version management and much more down the road.

**Comment by jheled** [comment]
I followed the four steps outlined for @lanegramling (in a python 2 virtualenv - not to mess my system)

I get the same error:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://youtu.be/G-Bn_kD6QN4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Git HEAD: a80358271
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-38-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube] G-Bn_kD6QN4: Downloading webpage
[youtube] G-Bn_kD6QN4: Downloading player f3c4e04d
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/joseph/Software/dl3/youtube-dl/youtube_dl/extractor/youtube.py", line 1361, in _decrypt_signature
    video_id, player_url, s
  File "/home/joseph/Software/dl3/youtube-dl/youtube_dl/extractor/youtube.py", line 1274, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/joseph/Software/dl3/youtube-dl/youtube_dl/extractor/youtube.py", line 1343, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/home/joseph/Software/dl3/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

.....

**Comment by nilbacardit26** [comment]
> Correction to [this helpful comment](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-995093694):
> 
> ```
> git clone --depth 1 --branch fix-function-sig-parser https://github.com/lanegramling/youtube-dl.git
> ```

As @DannyBen said, just make sure to be on the correct branch

**Comment by CagesThrottleUs** [comment]
@dirkf I have tried WinRAR, it's saying that it cannot open the exe but 7zip but only in read only format.

**Comment by RomainNicolaon** [comment]
> 



> Looks like youtube-dl needs to update the signature function regex.
> 
> There is no issue in yt-dlp, seems like this was avoided by [yt-dlp/yt-dlp#641](https://github.com/yt-dlp/yt-dlp/pull/641).
> 
> Back-porting them from yt-dlp works. Relevant code: https://github.com/yt-dlp/yt-dlp/blob/0bb322b9c0aebb7e0a93a5de1dbede4acdd10ff5/yt_dlp/extractor/youtube.py#L1828-L1845
> 
> Edit: Given the above patch by [yt-dlp/yt-dlp#641](https://github.com/yt-dlp/yt-dlp/pull/641), it may be possible that future player js versions may work again (but also break again at times for the same reason) with existing code.

If I understand correctly, we just need to wait and our bot will work again in the future ?

**Comment by DannyBen** [comment]
> If I understand correctly, we just need to wait and our bot will work again in the future ?

My understanding is similar, and I hope the near future 😄 
There seems to be a PR open - although in my experience it did not work well - so I guess the owners need to test/fix/merge it.

**Comment by kawowski** [comment]
I have two Macbook. One with 12.0.1 (21A559) Monterey and all youtube-dl is working fine. Second have 12.1 (21C52) and get this line (xcode/ffmpeg/youtube-dl/python are up to date)
<code>ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/Cellar/youtube-dl/2021.6.6_1/libexec/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.<code/>

Get also some update from Apple in settings "xcode developer update" so I was happy till update is finish cuz issue is still here. 
btw youtube-dl is the most powerfull tool and i LOVE IT.

**Comment by coletdjnz** [comment]
> > 
> 
> 
> 
> > Looks like youtube-dl needs to update the signature function regex.
> > 
> > There is no issue in yt-dlp, seems like this was avoided by [yt-dlp/yt-dlp#641](https://github.com/yt-dlp/yt-dlp/pull/641).
> > 
> > Back-porting them from yt-dlp works. Relevant code: https://github.com/yt-dlp/yt-dlp/blob/0bb322b9c0aebb7e0a93a5de1dbede4acdd10ff5/yt_dlp/extractor/youtube.py#L1828-L1845
> > 
> > Edit: Given the above patch by [yt-dlp/yt-dlp#641](https://github.com/yt-dlp/yt-dlp/pull/641), it may be possible that future player js versions may work again (but also break again at times for the same reason) with existing code.
> 
> If I understand correctly, we just need to wait and our bot will work again in the future ?

Yes, possibly. But it is likely this will occur again.

Though tbh if you can I'd just switch your dependency to yt-dlp (it's youtube-dl but actively maintained).

**Comment by DannyBen** [comment]
> switch your dependency to yt-dlp (it's youtube-dl but actively maintained).

This was a good advice. The fork works well.

_(although I am usually not a fan of using someone's repo to promote another, in this case I feel people are desperate for a quick solution that may never come.)_

**Comment by UnixCro** [comment]
🤣🤣🤣🤣🤣

**Comment by KSE-MD** [comment]
> Damn, this is a mess. I can't find any comment for a fix of youtube-dl installed with brew on macOS. Could someone point me to it?

https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-995093694 check this one out - worked for me

**Comment by TheSloPro** [comment]
yes the same issue here, please fix this asap or someone show me the way how can i fix this

**Comment by TheSloPro** [comment]
I need a solution for my Discord bot written in python please help me with this issue

**Comment by Jmackay82** [comment]
YTSearch has the same issue as well

C:\SYS586>c:\sys586\youtube-dl "ytsearch5:DO THEY KNOW ITS CHRISTMAS" --get-id --get-title
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1349, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1331, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\jsinterp.py", line 245, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Unsurprising, and also fixed by PR #30366.

When yt-dl processes a playlist, channel, or search, it tries to resolve metadata for each item found, similar to running yt-dl with `--list-formats` on the item. Then the release code fails because the media links have to be decoded and yt-dl fails to extract the necessary decoding script from the YT player JS.

**Comment by MaximFedarau** [comment]
Yeah, I recommend to use yt-dlp or smthn like this, because there is no bug and creators support their creation and i use module in js (yt-dlp-exec) , which has no changes with old and good youtube-dl-exec.

**Comment by UserSetting** [comment]
I have the same problem on Linux

$ youtube-dl -f 18 https://www.youtube.com/watch?v=yl8It450z-E
[youtube] yl8It450z-E: Downloading webpage
[youtube] yl8It450z-E: Downloading player f3c4e04d
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


===============================================


< Here is complete output with --verbose flag >
$ youtube-dl --verbose https://www.youtube.com/watch?v=yl8It450z-E
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=yl8It450z-E']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] yl8It450z-E: Downloading webpage
[youtube] yl8It450z-E: Downloading player f3c4e04d
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1623, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1358, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jimlynnjulian** [comment]
> You're up a creek without a paddle here, as we all are, to fend for ourselves. The master branch has not seen anything new in 6 months. So there is no existence of the one-step solution to reclaiming a binary you seek. You will have to follow the extra steps to create/collect one yourself if you want to use a binary version. He laid out a great step-by-step, unfortunately your only choices are A) follow it, B) wait indefinitely (likely months or never) for the miraculous return of someone that can pull it into master, or C) switch packages and update your codebases to support the migration. All of the options are bad options, unfortunately...

This brings up an issue in Github. Some of the better programs have dozens, even hundreds, of branches. A system of grading the variants would be useful, at least an icon in the listing to indicate no change/activity in the branch.

**Comment by 000011111111** [comment]
> Yeah, I recommend to use yt-dlp 

yt-dlp has the [same issue](https://github.com/blackjack4494/yt-dlc/issues/319)

**Comment by pythonmcpi** [comment]
> yt-dlp has the [same issue](https://github.com/blackjack4494/yt-dlc/issues/319)
I just installed the latest version from pip and it works. Make sure you've updated yt-dlp.

**Comment by 000011111111** [comment]
I am running  youtube-**dlc** version **2020.11.11-3** on MacOS 12.1

What version are you running specifically?

**Comment by jheled** [comment]
I switched to  yt-dlp. One unexpected benefit: download speed is much better (youtube-dl got slower and slower in the last few months. I thought this was google throttling me and shrugged)

**Comment by DannyBen** [comment]
> download speed is much better (youtube-dl got slower and slower in the last few months. I thought this was google throttling me and shrugged)

I had the exact same observation and experience.

**Comment by kawowski** [comment]
Official YT-DL working! Big big thanks for developers. Love u

**Comment by dirkf** [comment]
>I thought this was google throttling me and shrugged

It was, if you hadn't applied the patch from PR #30184.

**Comment by Jmackay82** [comment]
A Xmas bonus I thinks guys well done 👍🏼

**Comment by ealvan** [comment]
> Replace `youtube_dl/extractor/youtube.py` this file with [youtube.py.zip](https://github.com/ytdl-org/youtube-dl/files/7721294/youtube.py.zip) First Extract it

This comment works for me :)
