### ISSUE TITLE
Low download speed

### ISSUE THREAD

**Issue by KACTbIJIb** [ytdl-org/youtube-dl#30747]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
bash-5.0# youtube-dl -v https://youtu.be/-SQzCc1aW7Q
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://youtu.be/-SQzCc1aW7Q']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-4.19.0-9-amd64-x86_64-with
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] -SQzCc1aW7Q: Downloading webpage
[youtube] -SQzCc1aW7Q: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://rr4---sn-axq7sn7e.googlevideo.com/videoplayback?expire=1647366004&ei=FHswYsnOD8fp7ATUvr_AAw&ip=95.214.116.25&id=o-ALTdspqWbQJ8pbaIHSWxnkccC9EvBmgTILetwjy1pbXN&itag=22&source=youtube&requiressl=yes&mh=MS&mm=31%2C26&mn=sn-axq7sn7e%2Csn-c0q7lnse&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=3643750&vprv=1&mime=video%2Fmp4&ns=4J0DZTG4v-gAZesUeRLmtYcG&cnr=14&ratebypass=yes&dur=188.615&lmt=1616429245274372&mt=1647344223&fvip=5&fexp=24001373%2C24007246&c=WEB&txp=1211222&n=zdjjSX8Y71Zfox1AkXQh&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKnAV7frAYLVit70h6SXrUdUrUDrj-2yA0IjsHSiKZQjAiEAhRG7c-aFKocGHnepoRXFAoOdSqg4c7VnI2wl2DG_jHM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPVABjD5ns7Qx8CkLj83Q5TA6Gw5lvGMs3qaX9ShG4x3AiEA4c-aReEB0h0XTYhFwnvXQYTltRIXME4u9ATPWNN_3AA%3D'
[download] Resuming download at byte 915383
[download] Destination: Citroen xantia СЂР°Р±РѕС‚Р° РіРёРґСЂР°РІР»РёРєРё--SQzCc1aW7Q.mp4
[download]   5.6% of 48.57MiB at 79.54KiB/s ETA 09:50

```

## Description
Low download speed , 

Using youtube-dl to download and save videos in cold storage for api purposes.  
Due to project peculiarities(golang http server with lost source code) have no option to use yt-dlp or instal by apk or pip and make fixes. 
Is there any ways to build new binary file with fixes?

**Comment by NanaMizukiAnother7** [comment]
It was already fixed!: [Here](https://github.com/ytdl-org/youtube-dl/commit/af9e72507ea38e5ab3fa2751ed09ec88021260cb)

**Comment by KACTbIJIb** [comment]
It dont, look at speed.

**Comment by dirkf** [comment]
Look at [this block of the Makefile](https://github.com/ytdl-org/youtube-dl/blob/6508688e88c83bb811653083db9351702cd39a6a/Makefile#L60-L73).

**Comment by jprokos** [comment]
@NanaMizukiAnother7 Not fixed for me on macOS. All downloads are around 50KiB/s.
`409.10MiB at 49.60KiB/s ETA 01:56:31`

**Comment by dirkf** [comment]
Wait for the next release, or install from the GitHub repo using _pip_, or get a version from @KACTbIJIb if the hint above leads to success.

**Comment by KACTbIJIb** [comment]
thanks problem fixed.
