### ISSUE TITLE
YouTube 403 forbidden error on audio urls

### ISSUE THREAD

**Issue by ReenigneArcher** [ytdl-org/youtube-dl#32882]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Did something change in the YouTube audio formats, or are they returned differently than before? After merging https://github.com/ytdl-org/youtube-dl/commit/e1b3fa242cb94eb9dc949ab3f2cace91c46f11bf into my codebase, I am getting (somewhat) random failures, but still very repeatable. I wasn't getting these errors with the previous version of ytdl, but there was a new error (https://github.com/ytdl-org/youtube-dl/issues/32842#issuecomment-2247729123) so had to update.

Plex is giving me 406 (unacceptable) errors when I try to upload the audio.

```txt
2024-07-26 20:31:01,164 (1e38) :  ERROR (logkit:22) - 7: Error uploading media: (406) not_acceptable; http://127.0.0.1:32400/library/metadata/7/themes?url=https%3A%2F%2Frr2---sn-vgqsknll.googlevideo.com%2Fvideoplayback%3Fsparams%3Dexpire%252Cei%252Cip%252Cid%252Citag%252Csource%252Crequiressl%252Cxpc%252Cbui%252Cspc%252Cvprv%252Csvpuc%252Cmime%252Cns%252Crqh%252Cgir%252Cclen%252Cdur%252Clmt%26ei%3DdwekZoOfFMiL2_gPr9aZ8QY%26ip%3D<ip_address>%26clen%3D2952380%26spc%3DNO7bAUSfQKp7wA51RtQGKsRLBRf5mthsur--MRW5fbsriZPkNA1qre4UysJp%26id%3Do-AAoY5UDjTl1nbz2ILx_0-6f07PC6a8wTiWVAlOzqqb7U%26keepalive%3Dyes%26svpuc%3D1%26gir%3Dyes%26xpc%3DEgVo2aDSNQ%253D%253D%26requiressl%3Dyes%26source%3Dyoutube%26mv%3Du%26sig%3DAJfQdSswRQIhAMf8bjXRaGzgiRSBkOqQ_D39zP9NvzqawnrrT5DUi7FiAiB5sA67GgEuGddyT9dBkO93JerPVjcdWgiGzv499zHq4A%253D%253D%26dur%3D185.852%26ns%3DsfVMzFqD1xnov-0SyNvSksYQ%26vprv%3D1%26lsig%3DAGtxev0wRQIhALDSyv0QtzedMTElYBf8wrYFLVu9AVKMUkS73YdG0JmCAiB1MAf-1V11K54VOSB7cgbzRiqKJlpJmgEwfMoqD0sIog%253D%253D%26lsparams%3Dmh%252Cmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpl%26lmt%3D1381172018924357%26c%3DWEB%26sefc%3D1%26expire%3D1722047447%26mime%3Daudio%252Fmp4%26fvip%3D1%26rqh%3D1%26itag%3D140%26mm%3D31%252C29%26mn%3Dsn-vgqsknll%252Csn-vgqsrnsr%26mh%3DRH%26n%3DByy7QEICFdfW5A%26mt%3D1722025513%26bui%3DAXc671J3DF8IaVyrVeX7P2gjoWIta83r8-VJE-frLLoYb-Qu34nQWYMq_tCvsDUUawSv_qeOTvQLUkSo%26pl%3D23%26ms%3Dau%252Crdu%26mvi%3D2 <html><head><title>Not Acceptable</title></head><body><h1>406 Not Acceptable</h1></body></html>
```

Here is my code for getting the audio url: https://github.com/LizardByte/Themerr-plex/blob/c948caa73991e05cebe8b24b88bce5ccb6bede4c/Contents/Code/youtube_dl_helper.py#L133-L161

I tested locally, and I'm still getting audio urls, but could be in formats that aren't supported by Plex. Last update for Plex was July 9th, so nothing on their end changed in the last few days.

Any ideas?

**Comment by ReenigneArcher** [comment]
I dug a little deeper and the issue if that the url provided by youtube-dl is not accessible and gives a 403 error. This seems to be very random.

https://github.com/LizardByte/Themerr-plex/actions/runs/10119441078/job/27987941216?pr=486#step:8:276

This seems like a new development since the commit I linked above. Could youtube-dl validate that the url it gives is accessible before returning it? Possibly with some retry logic? I guess it may be too complex to validate all the format URLs.

**Comment by aiur-adept** [comment]
Could you post the original youtube url you're fetching so we could see what youtube-dl is returning/do some debugger-work?

**Comment by ReenigneArcher** [comment]
@aiur-adept sure, it can occur on seemingly any video. Here's two examples:

- https://www.youtube.com/watch?v=uXZd_W5B7N0
- https://www.youtube.com/watch?v=CIvUnfNiUXI

**Comment by aiur-adept** [comment]
Ah yeah, I've just seen the behaviour. It failed with 403 then after about 10 minutes it worked. Weird that they're sending a 403 when it's likely a rate limit. I'm not sure how to solve this as having the process wait for 10 minutes on a 403 isn't really a good solution.

**Comment by dirkf** [comment]
If you are post-processing the download URLs, you could try using the equivalent back-up URL (specified in its query parameters) on unexpected 403, or 4xx generally. This has so far been deemed too hard in yt-dl[p], as it would need a custom downloader; also AFAIK no-one has conclusively shown that the backup URL work better than the original one.

The algorithm for generating the backup URL is in an old issue (also at yt-dlp) which I expect I can find if you can't.

**Comment by ReenigneArcher** [comment]
I tried a small retry loop in my code as well, and it might have helped... still testing though.

I also tried not using a cookie file after seeing this: https://github.com/yt-dlp/yt-dlp/issues/10046 ... that also may have helped... still testing that too.

> Weird that they're sending a 403 when it's likely a rate limit.

From what I can see this is kind of standard for google products.


@dirf, I am not using youtube-dl to do the downloading, and I'm handling that on my own. I did see this https://github.com/yt-dlp/yt-dlp/issues/4100#issuecomment-1159457298 I'm not sure I 100% understand though.

**Comment by ReenigneArcher** [comment]
What's the algorithm for generating the backup url?

**Comment by dirkf** [comment]
Probably [this PR](https://github.com/yt-dlp/yt-dlp/pull/5639) is the best source.

**Comment by ReenigneArcher** [comment]
No luck: https://github.com/LizardByte/Themerr-plex/pull/486/commits/81df3d28c70213bb262ca1cff32c8f99140824b1

**Comment by ginahoy** [comment]
Don't want to start a new thread on an issue others are already reporting, but I'm confused as to which build I should download. 

I just ran into the '403 forbidden error' when attempting to download a youtube audio file (m4a). My youtube-dl was out-of-date (2023) as I hadn't used in a while so I downloaded the latest daily @ https://github.com/ytdl-patched/youtube-dl (7/30), and I still get the error. I can't recall why I had that particular page bookmarked, but I realize there are multiple forks of this program and I honestly have no idea what I'm doing!

Assuming this error has been fixed (or even if not), I would be grateful if someone could point me to the best place to get updates going forward.  Thx

**Comment by tansy** [comment]
> if someone could point me to the best place to get updates going forward.

https://github.com/ytdl-org/ytdl-nightly/releases

**Comment by JstaClarkey** [comment]
I found that the issue was at least partially because of m4a chosen as the best audio format. If I force it with 'bestaudio[ext=webm]' then previously 403 error'd URLs download with no issues. Still not a good solution because there's a few URLs with no webm format.

**Comment by ReenigneArcher** [comment]
@JstaClarkey thank you for that information. I'm also using m4a. I guess I will need to incorporate ffmpeg to solve this.

**Comment by seproDev** [comment]
This very much looks like the poToken experiment.
yt-dlp solved this by [retrying the web api](https://github.com/yt-dlp/yt-dlp/commit/8b8b442cb005a8d85315f301615f83fb736b967a) when the experiment is detected, since rollout is not yet at 100%.
In addition, yt-dlp [switched away from the web client](https://github.com/yt-dlp/yt-dlp/commit/efb42763dec23ccf6a2e3bac3afbfefce8efd012). As afaik. youtube-dl only support the web client, this will be more difficult to backport.

**Comment by dirkf** [comment]
Yes, I've made a WIP that tests for `poToken` and so it could be made to retry.

The multiple client thing is conceptually straightforward (ie, instead of a single result to be traversed there is a list of results) but also brings in some related catch-up issues like extractor args.

**Comment by ReenigneArcher** [comment]
@dirkf I'll be happy to test when it's ready. My CI tests about 30 videos, so it's pretty easy to hit this error.

**Comment by dirkf** [comment]
My initial testing gives somewhat strange results. Getting the title from each item in a playlist brings up the poToken warning quite regularly. Downloading item 1 of the list works fine regardless of whether the warning appears.

Similar results with the two videos [above](https://github.com/ytdl-org/youtube-dl/issues/32882#issuecomment-2254157622).

**Comment by ReenigneArcher** [comment]
Do you have a live branch for this?

**Comment by dirkf** [comment]
Continued in #32905.
